services:
  dns:
    build: ./.docker/dns
    volumes:
      - ./dns:/app
      - ./.common:/app/.common
    ports:
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"
      - "${ROUTER_OUTER_IP}:53535:53535"
    user: root
    command: /app/run.sh
    environment:
      INNER_IP: ${ROUTER_INNER_IP}
      OUTER_IP: ${ROUTER_OUTER_IP}
      LOCAL_DOMAIN_SUFFIX: ${LOCAL_DOMAIN_SUFFIX}
      NETWORK_IP: ${NETWORK_IP}
      SUBNET_MASK: ${SUBNET_MASK}
    depends_on:
      - rails
    restart: always

  dhcp:
    build: ./.docker/dhcp
    volumes:
      - ./dhcp:/app
      - ./.common:/app/.common
    network_mode: "host"
    user: root
    command: /app/run.sh
    environment:
      ROUTER_IP: ${ROUTER_INNER_IP}
      HOST_NAME: ${ROUTER_HOST_NAME}
      DOMAIN_SUFFIX: ${LOCAL_DOMAIN_SUFFIX}
      SOA_DATA: ${LOCAL_SOA}
      NETWORK_IP: ${NETWORK_IP}
      SUBNET_MASK: ${SUBNET_MASK}
    depends_on:
      - rails
    restart: always

  web:
    build: ./.docker/web
    volumes:
      - ./web:/app
      - ./.common:/app/.common
    ports:
      - "0.0.0.0:80:8000"
    user: root
    command: /app/run.sh
    depends_on:
      - rails
    restart: always

  rails:
    build: ./.docker/rails
    volumes:
      - ./rails:/app
      - ./.common:/app/.common
    ports:
      - "127.0.0.1:3000:3000"
    user: root
    command: /app/run.sh
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      LOCAL_SOA: ${LOCAL_SOA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: always

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

volumes:
  db_data:
    driver: local