version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../.env:/workspaces/ddns/.env
      - ../dotenv-props.txt:/workspaces/ddns/dotenv-props.txt
      - ../.docker/dhcp:/workspaces/ddns/.docker/dhcp:cached
      - ../.docker/dns:/workspaces/ddns/.docker/dns:cached
      - ../.docker/rails:/workspaces/ddns/.docker/rails:cached
      - ../dhcp:/workspaces/ddns/dhcp:cached
      - ../dns:/workspaces/ddns/dns:cached
      - ../rails:/workspaces/ddns/rails:cached
      - ../.git:/workspaces/ddns/.git:cached
      - ../.gitignore:/workspaces/ddns/.gitignore:cached
      - ../docker-compose.yaml:/workspaces/ddns/docker-compose.yaml:cached
      - ../.devcontainer:/workspaces/ddns/.devcontainer:cached
      - ../.docker/.root/app:/home/vscode
    command: sleep infinity
    environment:
      RAILS_ENV: development
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      INNER_IP: ${ROUTER_INNER_IP}
      OUTER_IP: ${ROUTER_OUTER_IP}
      ROUTER_IP: ${ROUTER_INNER_IP}
      NETWORK_IP: ${NETWORK_IP}
      SUBNET_MASK: ${SUBNET_MASK}
      LOCAL_DOMAIN_SUFFIX: ${LOCAL_DOMAIN_SUFFIX}
      LOCAL_SOA: ${LOCAL_SOA}
    depends_on:
      - dns
      - dhcp

  dns:
    extends:
      file: ../docker-compose.yaml
      service: dns
    container_name: ddns-server-dns
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "${ROUTER_OUTER_IP}:53535:53535"
    depends_on:
      - rails

  dhcp:
    extends:
      file: ../docker-compose.yaml
      service: dhcp
    container_name: ddns-server-dhcp
    ports:
      - "6767:67/udp"
    depends_on:
      - rails

  rails:
    extends:
      file: ../docker-compose.yaml
      service: rails
    container_name: ddns-server-rails
    depends_on:
      - db

  db:
    extends:
      file: ../docker-compose.yaml
      service: db
    container_name: ddns-server-db

volumes:
  db_data:
    driver: local